SELECT
  CAST(donor_id AS BIGINT)               AS donor_id,
  CAST(registered_by_staff_id AS BIGINT) AS registered_by_staff_id,
  CAST(primary_contact_id AS BIGINT)     AS primary_contact_id,
  INITCAP(TRIM(name))                    AS name,
  CAST(age AS INT)                       AS age,
  INITCAP(TRIM(gender))                  AS gender,
  CAST(weight AS NUMERIC(5,2))           AS weight,
  UPPER(TRIM(blood_group))               AS blood_group,
  CAST(NULLIF(last_donation_date, '0000-00-00') AS DATE) AS last_donation_date,
  CAST(is_eligible AS BOOLEAN)           AS is_eligible,
  CAST(donations_count AS INT)           AS donations_count,
  LOWER(TRIM(contact_method_type))       AS contact_method_type,
  TRIM(contact_detail)                   AS contact_detail,
  LOWER(TRIM(donor_type))                AS donor_type,
  notes                                  AS notes,
  CAST(NULLIF(last_health_check_date, '0000-00-00') AS DATE) AS last_health_check_date,
  CAST(donation_frequency_allowed AS INT) AS donation_frequency_allowed,
  INITCAP(TRIM(location))                 AS location,
  CAST(days_since_last_donation AS INT)   AS days_since_last_donation,
  CAST(blood_group_A_plus AS BOOLEAN)   AS blood_group_A_plus,
  CAST(blood_group_O_minus AS BOOLEAN)  AS blood_group_O_minus,
  CAST(blood_group_B_plus AS BOOLEAN)   AS blood_group_B_plus,
  CAST(blood_group_AB_minus AS BOOLEAN) AS blood_group_AB_minus,
  CAST(blood_group_A_minus AS BOOLEAN)  AS blood_group_A_minus,
  CAST(blood_group_B_minus AS BOOLEAN)  AS blood_group_B_minus,
  CAST(blood_group_O_plus AS BOOLEAN)   AS blood_group_O_plus,
  CAST(blood_group_AB_plus AS BOOLEAN)  AS blood_group_AB_plus
  
FROM {{ source('raw', 'donors') }}
