CREATE TABLE raw.tasks (
  task_id     TEXT,  -- Unique identifier for each task
  description TEXT   -- Detailed description of the task
);
INSERT INTO raw.tasks (task_id, description) VALUES
(1, 'Blood collection'),
(2, 'Equipment maintenance'),
(3, 'Data entry'),
(4, 'Lab equipment calibration'),
(5, 'Blood typing and testing'),
(6, 'Inventory management'),
(7, 'Donor screening'),
(8, 'Quality control'),
(9, 'Regulatory compliance'),
(10, 'Patient data recording'),
(11, 'Blood collection'),
(12, 'Equipment maintenance'),
(13, 'Data entry'),
(14, 'Lab equipment calibration'),
(15, 'Blood typing and testing'),
(16, 'Inventory management'),
(17, 'Donor screening'),
(18, 'Quality control'),
(19, 'Regulatory compliance'),
(20, 'Patient data recording'),
(21, 'Staff training'),
(22, 'Blood storage management'),
(23, 'Donation appointment scheduling'),
(24, 'Public awareness campaign'),
(25, 'Emergency response planning'),
(26, 'Medical record keeping'),
(27, 'Facility cleaning and sterilization'),
(28, 'Supply chain coordination'),
(29, 'Health and safety audit'),
(30, 'Volunteer coordination');